# -*- coding: utf-8 -*-
s=input("введите строку состоящюю из минимум 7 цифр начиная с нуля ")
print(s[3])
print (s[-2])
print(s[0:5])
print(s[0:-2])
print(s[::2])
print(s[1::2])
print(s[::-1])
print(s[::-2])
print(len(s))